{% set version = "0.2.1" %}

package:
  name: oxrdflib
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/o/oxrdflib/oxrdflib-{{ version }}.tar.gz
    sha256: 0e216500eca1c22a7b4f1cc911b76986302db230fb6c54da25da4482e0c7bb5e
  - folder: src
    url: https://github.com/oxigraph/oxrdflib/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 08f60a100158ac0ecb1d76df6f3e5b90320a0fde93e08f6878e9b68b7ed9f975

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pyoxigraph >=0.2,<0.3
    - python >=3.7
    - rdflib >=6.0,<7.0

test:
  source_files:
    - src/tests
  imports:
    - oxrdflib
  commands:
    - pip check
    - cd src/tests
    - pytest --cov oxrdflib --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under 87
  requires:
    - pip
    - pytest-cov
    - requests

about:
  home: https://github.com/oxigraph/oxrdflib
  summary: rdflib stores based on pyoxigraph
  dev_url: https://github.com/oxigraph/oxrdflib
  license: BSD-3-Clause
  license_file: src/LICENSE.md

extra:
  recipe-maintainers:
    - bollwyvl
