{% set version = "0.3.3" %}

package:
  name: oxrdflib
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/o/oxrdflib/oxrdflib-{{ version }}.tar.gz
    sha256: 66cdbb51f7fee6630b0a13d7a36e228eaf7219daa31e14eb5d28ad367ec66daa
  - folder: src
    url: https://github.com/oxigraph/oxrdflib/archive/refs/tags/v{{ version }}.tar.gz
    sha256: ec6b5ffd907b57dae039b8508d826759ae5cc5f18e0abe858fd94a37efabb629

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - pyoxigraph >=0.3.14,<0.4
    - python >=3.7
    - rdflib >=6.3,<7.0

test:
  source_files:
    - src/tests
  imports:
    - oxrdflib
  commands:
    - pip check
    - cd src && pytest -vv --cov=oxrdflib --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=86
  requires:
    - pip
    - pytest-cov
    - requests

about:
  home: https://github.com/oxigraph/oxrdflib
  summary: rdflib stores based on pyoxigraph
  dev_url: https://github.com/oxigraph/oxrdflib
  license: BSD-3-Clause
  license_file: src/LICENSE.md

extra:
  recipe-maintainers:
    - bollwyvl
